#!/bin/bash
docker run --name ci-explore-demos-java-pipeline \
  --detach --rm \
  --network ci \
  --publish 8080:8080 --publish 6300:6300 \
  --env JAVA_OPTS="-javaagent:/jacocoagent.jar=output=tcpserver,address=*,port=6300" \
  explore/explore-demos-java-pipeline:latest
